# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show env
        run: |
          python -V
          which python
          pip -V
          uname -a

      - name: Install package + dev deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev, test]"
          python -c "import sys,sysconfig; print('site-packages:', sysconfig.get_paths()['purelib'])"

      - name: List tree (src & tests)
        run: |
          ls -la
          ls -la src || true
          ls -la src/nifti_finder || true
          ls -la tests || true

      - name: Freeze deps
        run: pip freeze

      - name: Run pytest (verbose on failure)
        run: |
          pytest -q || (echo '--- RERUN VERBOSE ---' && pytest -vv)

